### ISSUE TITLE
Validate the plugin with Grafana 3.1.0

### ISSUE THREAD

**Issue by FlorianLautenschlager** [ChronixDB/chronix.grafana#13]
Use Grafana 3.1.0 for development.

- [x] Check on Windows
- [x] Check on Linux

**Comment by sciffer** [comment]
Does not work for me

**Comment by FlorianLautenschlager** [comment]
Thanks, i will investigate on this later.

**Comment by sciffer** [comment]
BTW, It might be the result of using Logstash chronix output plugin.

**Comment by FlorianLautenschlager** [comment]
So what i did (worked on windows):

1. Downloaded Grafana 3.1, Chronix-Server 0.3, and Chronix-Grafana
2. Copied the Chronix-Grafana directory to Grafana
3. Created a datasource for Chronix. 
![image](https://cloud.githubusercontent.com/assets/3796738/17105531/f62a601c-5287-11e6-9f77-4a19b21c7987.png)
4. Created a dashboard 
![image](https://cloud.githubusercontent.com/assets/3796738/17105559/0edb27cc-5288-11e6-9c6a-e465e1d3bec6.png)

To your point with the tailing three zeros. Grafana returns unix time (seconds since 1970) while Chronix wants milliseconds since 1970 i simply multiplied it with 1000. 

*Note:* What i not tested is the pipeline with Chronix-Logstash. And that one have to enter "metric:" is definitely an issue. Thanks @sciffer 
Otherwise one will see this error:
![image](https://cloud.githubusercontent.com/assets/3796738/17105782/ed71e1e2-5288-11e6-8b3c-ed00016f34dc.png)

**Comment by FlorianLautenschlager** [comment]
Created an issue for the "no field name specified in query..." see #14

**Comment by FlorianLautenschlager** [comment]
Chronix-Grafana and Grafana 3.1 also works on Linux. 
Closing this issue.
