### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by phxql** [ChronixDB/chronix.grafana#23]
Hi, I can't get the Chronix Datasource to work.

Steps i have done:

1. Installed Grafana
2. cd grafana-3.1.1-1470047149/public/app/plugins/datasource/
3. git clone git@github.com:ChronixDB/chronix.grafana.git
4. Start grafana: ./bin/grafana-server
5. Add Chronix datasource

The following error appears in a red bubble: "Plugin Error
Error loading http://localhost:3000/public/app/plugins/datasource/chronix/module.js"

What am I doing wrong?

**Comment by phxql** [comment]
I think i got it working with:

1. Install plugin in grafana-3.1.1-1470047149/public/app/plugins/datasource/chronix
2. run npm install
3. run npm run build
4. move contents from dist folder to grafana-3.1.1-1470047149/public/app/plugins/datasource/chronix

**Comment by FlorianLautenschlager** [comment]
@defaude could you confirm this?

**Comment by defaude** [comment]
Ya, the install doc is still b0rked. Will update that right away :)

* unzip Grafana wherever you want
* clone the chronix.grafana repo into <GRAFANA-DIR>/data/plugins/
* start grafana (from the root dir): `./bin/grafana-server` - or `bin\grafana-server.exe` if you're on Windows
* enjoy

**Comment by FlorianLautenschlager** [comment]
Additional: The correct way to load plug-ins in grafana is to put them relative to bin/grafana-server.exe in the directory called data/plugins

**Comment by phxql** [comment]
Thanks, will try that!

**Comment by defaude** [comment]
No need to do the whole npm jazz if you just want to **use** chronix.grafana. Since there's a `dist` folder in the checked out repo, Grafana will automagically use that content.

**Comment by defaude** [comment]
Next step: Tell the Grafana Marketplace to use the tags / releases from this repo ;)

**Comment by FlorianLautenschlager** [comment]
Prior to this we have to do some "basic" stuff ;-)

**Comment by defaude** [comment]
@phxql works now?

**Comment by phxql** [comment]
Nope.

Installed grafana, created data/plugins and ran a git clone in that. (the git workspace is now in /home/moe/tmp/grafana-3.1.1-1470047149/data/plugins/chronix.grafana/)

On the datasource screen in Grafana the Chronix datasource isn't listed.

**Comment by defaude** [comment]
Aaah wait. The whole "copy to data/plugins/" thing should read as "copy to your grafana installation's plugin directory" ;)

On Linux (depending how you've installed it), the plugins directory might be `/var/lib/grafana/plugins` - what happens if you clone Chronix.grafana into that directory?

**Comment by phxql** [comment]
```
INFO[11-16|11:08:32] Path Plugins                             logger=settings path=data/plugins
```

1. cd data/plugins
2. git clone git@github.com:ChronixDB/chronix.grafana.git
3. Works

Thanks! Should i provide a pull request for the readme?

**Comment by FlorianLautenschlager** [comment]
Yeah, feel free!

**Comment by FlorianLautenschlager** [comment]
@phxql could you please provide a pr closing this issue?

**Comment by phxql** [comment]
Readme has already been updated (1c1bf1983885759193150e2995bcd0049029e1e0). Issue is resolved.
